
version: '3'

services:
  database:
    image: postgres
    container_name: pg_container
    volumes:
       - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: chat_container
    links:
     - database
    environment:
      - PASSWORD=postgresql1112
      - USER=postgresql
      - NAME=chatapplication
      - HOST=db
      - PORT=5432
    depends_on:
      - database

volumes:
  pgdata: {}
